Bug 1823277 [wpt PR 39073] - Fix console error in anonymous-iframe/worker-cookies SW test, a=testonly
Automatic update from web-platform-tests
Fix console error in anonymous-iframe/worker-cookies SW test

Fixes the following console error that appears when running
anonymous-iframe/worker-cookies.tentative.https.window.html?worker=service_worker:

CONSOLE ERROR: Uncaught (in promise)
  ReferenceError: add_completion_callback is not defined

Bug: None
Change-Id: I613b8adf0105d0798c6807896437d12f3c10e22e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4350542
Commit-Queue: Arthur Sonzogni <arthursonzogni@chromium.org>
Reviewed-by: Arthur Sonzogni <arthursonzogni@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1119288}

--

wpt-commits: 1b93b258c8257e5361c2f41c7dd1b1a9e43f8dea
wpt-pr: 39073