Bug 1858215 [wpt PR 42120] - browser: Pass -ErrorAction to Get-Item PowerShell call, a=testonly
Automatic update from web-platform-tests
browser: Pass -ErrorAction to Get-Item PowerShell call (#42120)

By default, PowerShell script errors are shown but do not stop script
execution. This meant that even if a given binary did not exist,
`_get_fileversion()` would not return None because the Get-Item was not the
latest thing to run. The error messages would end up looking very cryptic:

    0:02.08 INFO Version Get-Item could not be formatted for build matching.
    Traceback (most recent call last):
      File "C:\Users\rkubodac\src\wpt\wpt", line 10, in <module>
        wpt.main()
      File "C:\Users\rkubodac\src\wpt\tools\wpt\wpt.py", line 233, in main
        rv = script(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\rkubodac\src\wpt\tools\wpt\run.py", line 914, in run
        wptrunner_kwargs = setup_wptrunner(venv, **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\rkubodac\src\wpt\tools\wpt\run.py", line 887, in setup_wptrunner
        setup_cls.setup(kwargs)
      File "C:\Users\rkubodac\src\wpt\tools\wpt\run.py", line 190, in setup
        self.setup_kwargs(kwargs)
      File "C:\Users\rkubodac\src\wpt\tools\wpt\run.py", line 376, in setup_kwargs
        webdriver_binary = self.browser.install_webdriver(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\rkubodac\src\wpt\tools\wpt\browser.py", line 1259, in install_webdriver
        chromedriver_path = self.install_webdriver_by_version(version, dest, channel)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\rkubodac\src\wpt\tools\wpt\browser.py", line 1269, in install_webdriver_by_version
        url = self._get_webdriver_url(version, channel)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\rkubodac\src\wpt\tools\wpt\browser.py", line 995, in _get_webdriver_url
        raise ValueError(f"Unknown version format: {version}")
    ValueError: Unknown version format: Get-Item

Explicitly invoke Get-Item with `-ErrorAction Stop` so that any errors
there (including the item not being found) cause script execution to stop
and the call to `call()` to throw a `subprocess.CalledProcessError` as
expected.
--

wpt-commits: f3a84a31e309f9e7ad7e85122323d344ad80a04a
wpt-pr: 42120